apiVersion: v1
kind: Service
metadata:
  name: {{ include "lecture.api.name" . }}
  labels:
    {{- include "lecture.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http

