apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: lecture
  namespace: custom-app
spec:
  parentRefs:
    - name: core-service-gateway
      namespace: gateway
      sectionName: https
  hostnames:
    - learning.pic-aichem.online
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /assets
      backendRefs:
        - name: lecture
          port: 8080

    - matches:
        - path:
            type: PathPrefix
            value: /api
      backendRefs:
        - name: lecture
          port: 8080

    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: lecture
          port: 80
