apiVersion: v1
kind: Service
metadata:
  name: lecture
  namespace: custom-app
  labels:
    app.kubernetes.io/name: lecture
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: lecture
  ports:
    - name: web
      port: 80
      targetPort: web
    - name: api
      port: 8080
      targetPort: api
